### ISSUE TITLE
the rule title could be based on the mode combinaison

### ISSUE THREAD

**Issue by bourgeoa** [Otto-AA/solid-acl-parser#4]
Mashlib uses an alphabetical mode combinaison that I find quite clean and explicit : 

> @prefix : <#>.
@prefix n0: <http://www.w3.org/ns/auth/acl#>.
@prefix n1: <http://xmlns.com/foaf/0.1/>.
@prefix c: </profile/card#>.
@prefix c0: <https://example.solid.community/profile/card#>.

> **:Append**
    a n0:Authorization;
    n0:accessTo <text4.txt>;
     n0:agentClass n0:AuthenticatedAgent;
     n0:mode n0:Append.
**:AppendRead**
    a n0:Authorization;
    n0:accessTo <text4.txt>;
    n0:agentClass n1:Agent;
    n0:mode n0:Append, n0:Read.
**:ControlReadWrite**
    a n0:Authorization;
    n0:accessTo <text4.txt>;
    n0:agent c:me;
    n0:mode n0:Control, n0:Read, n0:Write.
**:Read**
    a n0:Authorization;
    n0:accessTo <text4.txt>;
    n0:mode n0:Read;
    n0:origin <https://www.bourgeoa.ga>.
**:ReadWrite**
    a n0:Authorization;
    n0:accessTo <text4.txt>;
    n0:agent c0:me;
    n0:mode n0:Read, n0:Write.

**Comment by Otto-AA** [comment]
Thanks, that's a good suggestion. I think I will do this, with the little change that default rules will also be prepended with default (e.g. `DefaultRead`).
